# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blur.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nblur.proto\x12\x04\x62lur\"\x1b\n\x0bpingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\x04\x42lur\x12/\n\x04Ping\x12\x11.blur.pingRequest\x1a\x12.blur.PingResponse\"\x00\x42\x06Z\x04\x62lurb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blur_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004blur'
  _globals['_PINGREQUEST']._serialized_start=20
  _globals['_PINGREQUEST']._serialized_end=47
  _globals['_PINGRESPONSE']._serialized_start=49
  _globals['_PINGRESPONSE']._serialized_end=80
  _globals['_BLUR']._serialized_start=82
  _globals['_BLUR']._serialized_end=137
# @@protoc_insertion_point(module_scope)
