// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: blur.proto

package blur

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Blur_Ping_FullMethodName = "/blur.Blur/Ping"
)

// BlurClient is the client API for Blur service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlurClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type blurClient struct {
	cc grpc.ClientConnInterface
}

func NewBlurClient(cc grpc.ClientConnInterface) BlurClient {
	return &blurClient{cc}
}

func (c *blurClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Blur_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlurServer is the server API for Blur service.
// All implementations must embed UnimplementedBlurServer
// for forward compatibility
type BlurServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedBlurServer()
}

// UnimplementedBlurServer must be embedded to have forward compatible implementations.
type UnimplementedBlurServer struct {
}

func (UnimplementedBlurServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBlurServer) mustEmbedUnimplementedBlurServer() {}

// UnsafeBlurServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlurServer will
// result in compilation errors.
type UnsafeBlurServer interface {
	mustEmbedUnimplementedBlurServer()
}

func RegisterBlurServer(s grpc.ServiceRegistrar, srv BlurServer) {
	s.RegisterService(&Blur_ServiceDesc, srv)
}

func _Blur_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlurServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blur_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlurServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blur_ServiceDesc is the grpc.ServiceDesc for Blur service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blur_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blur.Blur",
	HandlerType: (*BlurServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Blur_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blur.proto",
}
